pipeline {

    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
when{ branch 'amitbranch' }
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
	when{
		branch 'master'
	}
            steps {
                echo 'Deploying....'
            }
        }
    }
}
